### ISSUE TITLE
Doc Question; New Menu Tools / ExtensionDeveloper is only new item in Firefox ? 

### ISSUE THREAD

**Issue by AnneTheAgile** [brettz9/dev-assistant#2]
I poked around and it seems like the real thing remaining without the extension development tools is the new menu. 
https://github.com/brettz9/dev-assistant/search?utf8=%E2%9C%93&q=menu

Is that right? If so perhaps I can add to your readme?
Thank you for hosting on Github where it's so easy to say hi!

Refs; 
1.[]The code for the Debug prefs is here; 
````
var debuggingPrefs = ["nglayout.debug.disable_xul_cache", "javascript.options.showInConsole", "browser.dom.window.dump.enabled"];
````
https://github.com/brettz9/dev-assistant/blob/262db68d6452032ead7510ef3107de92894afc87/content/extensiondevOverlay.js#L6

2.[] ; ; ;My SO post that brought me here ; ; ; ; ; ; ;  X.javascript - How to test Copy Paste in Firefox Developer Tools Web Console? - Stack Overflow
http://stackoverflow.com/questions/27736195/how-to-test-copy-paste-in-firefox-developer-tools-web-console/27760510#27760510

3.[] ; ; ; ;Official Firefox addon development info  ; ; ; ; ; ;  X.Setting up an extension development environment - Mozilla | MDN
https://developer.mozilla.org/en-US/Add-ons/Setting_up_extension_development_environment?redirectlocale=en-US&redirectslug=Setting_up_extension_development_environment#Development_preferences

**Comment by brettz9** [comment]
Sorry, Anne, I guess because I have not opted to receive emails for repos I'm watching, I don't even get notified for issues added to my own repos (until I comment in them)!

Firstly, let me suggest persisting to figure out their official Scratchpad since, unlike our project, they are doing ongoing development on it. You can install the add-on [Noitidart mentioned](https://addons.mozilla.org/en-US/firefox/addon/devprefs/) (or apparently [this one](https://addons.mozilla.org/en-US/firefox/addon/developer-profile/) too), or in this case, you really only need to change this setting after visiting `about:config`: `devtools.chrome.enabled` to `true`. That causes an "Environment" menu to be added to Scratchpad (be sure to open a new Scratchpad after changing the about:config setting).

That being said, since it was an easy fix for me to confirm, I've added the new options. I'm not pushing an update to AMO now though, since I really should review PR #1 , and I'm not sure when I'll have time to sit and look at that. Marking as closed since the master branch has the fix now though feel free to keep commenting here.
